# Generated by Django 5.2.7 on 2025-12-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('apartment', 'Байрны захиалга'), ('commercial', 'Худалдааны төв түрээс')], max_length=20, verbose_name='Үйлчилгээний төрөл')),
                ('phone', models.CharField(help_text='8 оронтой утасны дугаар', max_length=8, verbose_name='Утасны дугаар')),
                ('date', models.DateField(verbose_name='Огноо')),
                ('time', models.CharField(help_text='Цагийн формат: HH:MM', max_length=5, verbose_name='Цаг')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Нэмэлт мэдээлэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчлэгдсэн огноо')),
            ],
            options={
                'verbose_name': 'Уулзалтын хүсэлт',
                'verbose_name_plural': 'Уулзалтын хүсэлтүүд',
                'ordering': ['-created_at'],
            },
        ),
    ]
