# Generated by Django 5.2.7 on 2025-12-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(help_text='Хэд хэдэн үйлчилгээний төрөл сонгосон бол таслалаар тусгаарлагдана (жишээ: apartment,commercial)', max_length=100, verbose_name='Үйлчилгээний төрөл'),
        ),
    ]
