# Generated by Django 5.2.7 on 2025-12-03 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Гарчиг')),
                ('excerpt', models.TextField(verbose_name='Товч агуулга')),
                ('content', models.TextField(blank=True, verbose_name='Бүрэн агуулга')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Огноо')),
                ('read_time', models.CharField(default='5 мин', max_length=20, verbose_name='Унших хугацаа')),
                ('views', models.IntegerField(default=0, verbose_name='Үзсэн тоо')),
                ('image', models.URLField(blank=True, max_length=500, verbose_name='Зургийн URL')),
                ('featured', models.BooleanField(default=False, verbose_name='Онцлох')),
                ('author', models.CharField(default='Энканто Сентро медиа баг', max_length=100, verbose_name='Зохиогч')),
                ('tags', models.CharField(blank=True, help_text='Таг-уудыг таслалаар тусгаарлана', max_length=255, verbose_name='Таг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Мэдээ',
                'verbose_name_plural': 'Мэдээнүүд',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
