# Generated by Django 5.2.7 on 2025-12-03 07:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Бүрэн агуулга'),
        ),
    ]
