# Generated by Django 5.2.7 on 2025-12-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Брэндийн нэр')),
                ('image', models.URLField(max_length=500, verbose_name='Зургийн URL')),
                ('order', models.IntegerField(default=0, help_text='Дарааллын тоо бага байх тусам эхэнд харагдана', verbose_name='Дараалал')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Брэнд',
                'verbose_name_plural': 'Брэндүүд',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Гарчиг')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Дэд гарчиг')),
                ('image', models.URLField(max_length=500, verbose_name='Зургийн URL')),
                ('order', models.IntegerField(default=0, help_text='Дарааллын тоо бага байх тусам эхэнд харагдана', verbose_name='Дараалал')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Давхрын төлөвлөлт',
                'verbose_name_plural': 'Давхрын төлөвлөлтүүд',
                'ordering': ['order', 'id'],
            },
        ),
    ]
