# Generated by Django 5.2.7 on 2025-12-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='brands/', verbose_name='Зураг'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='image',
            field=models.ImageField(upload_to='floorplans/', verbose_name='Зураг'),
        ),
    ]
